@startuml Role Definition
!pragma teoz true

' Title
title 使用者更新基本資料

' ------- 全域樣式 -------
skinparam backgroundColor #fefefe
skinparam roundcorner 15
skinparam DefaultFontSize 14
skinparam DefaultFontName Arial

' ------- Actor -------
actor FE    as "FrontEnd [Actor]"

' ------- Module -------
' ─ Metadata Management ─
box "Metadata Mgt Module [Module]" #LightGreen
	participant Meta_UM as "UserManager [Actor]"
end box

autonumber 1
FE -> Meta_UM: /update_user
activate Meta_UM
Meta_UM -> Meta_UM: 找對應的 user metadata 並更新
Meta_UM --> FE: 更新成功
deactivate Meta_UM

@enduml
